name: ticketing_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2


# Add regular dependencies here.
dependencies:
   shelf: ^1.4.1
   shelf_router: ^1.1.3
   sqlite3: ^1.3.0
   path: ^1.9.0
   uuid: ^4.0.0
   dart_jsonwebtoken: ^2.7.0
    

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
